name: Deploy to EC2
on:
  workflow_run:
    workflows: ["Python Tests"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy_infra:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
          
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7
          
      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init
         
      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve
        
      - name: Get Instance IP
        id: get-ip
        working-directory: ./terraform
        run: |
          IP=$(terraform output -raw instance_public_ip | tr -d '\n' | cut -d':' -f1)
          echo $IP
          echo "IP is: $IP"
          echo "instance_ip=$IP" >> "$GITHUB_OUTPUT"

        
      - name: Setup SSH Key
        working-directory: ./terraform
        run: |
          mkdir -p ~/.ssh
          terraform output -raw private_key > ~/.ssh/private_key.pem
          chmod 600 ~/.ssh/private_key.pem
          
      - name: Debug Info
        run: |
          echo "Using IP: ${{ steps.get-ip.outputs.instance_ip }}"
          
      - name: Wait for instance
        run: |
          echo "Waiting for instance to be ready..."
          sleep 30
        
      - name: Deploy application
        env:
          INSTANCE_IP: ${{ steps.get-ip.outputs.instance_ip }}
        run: |
          echo "Deploying to $INSTANCE_IP"
          
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/private_key.pem ubuntu@$INSTANCE_IP 'echo "Connection test"' || {
            echo "Failed to connect to instance"
            exit 1
          }
          
          scp -o StrictHostKeyChecking=no -i ~/.ssh/private_key.pem -r ./* ubuntu@$INSTANCE_IP:/home/ubuntu/app || {
            echo "Failed to copy files"
            exit 1
          }
          
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/private_key.pem ubuntu@$INSTANCE_IP '
            cd /home/ubuntu/app &&
            sudo apt-get update &&
            sudo apt-get install -y python3-pip &&
            pip3 install -r requirements.txt &&
            nohup python3 app.py > app.log 2>&1 &
          ' || {
            echo "Failed to set up application"
            exit 1
          }