name: Deploy to EC2
on:
  workflow_run:
    workflows: ["Python Tests"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy_infra:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
          
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7
          
      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init
         
      - name: Terraform Apply and Get IP
        id: tf-apply
        working-directory: ./terraform
        run: |
          terraform apply -auto-approve
          INSTANCE_IP=$(terraform output -raw instance_public_ip)
          echo "ip=$INSTANCE_IP" >> $GITHUB_OUTPUT
        
      - name: Setup SSH Key
        working-directory: ./terraform
        run: |
          mkdir -p ~/.ssh
          terraform output -raw private_key > ~/.ssh/private_key.pem
          chmod 600 ~/.ssh/private_key.pem
          
      - name: Wait for instance
        run: |
          echo "Waiting for instance ${{ steps.tf-apply.outputs.ip }} to be ready..."
          sleep 30
        
      - name: Deploy application
        working-directory: ./terraform
        run: |
          echo "Starting deployment to ${{ steps.tf-apply.outputs.ip }}"
          # בדיקת קישוריות
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/private_key.pem ubuntu@${{ steps.tf-apply.outputs.ip }} 'echo "Connection test"' || exit 1
          
          # העלאת הקבצים
          scp -o StrictHostKeyChecking=no -i ~/.ssh/private_key.pem -r ../* ubuntu@${{ steps.tf-apply.outputs.ip }}:/home/ubuntu/app
          
          # התקנה והפעלה
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/private_key.pem ubuntu@${{ steps.tf-apply.outputs.ip }} '
            cd /home/ubuntu/app &&
            sudo apt-get update &&
            sudo apt-get install -y python3-pip &&
            pip3 install -r requirements.txt &&
            nohup python3 app.py > app.log 2>&1 &
          '